version: '3.9'

services:
  db:
    container_name: mikti-db
    image: postgres:16-alpine
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mikti-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DBPASS}
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_DB=${DBNAME}
      - DATABASE_HOST=${DBHOST}
    networks:
      - mikti

  api:
    image: irvanhau/ticketing-app
    container_name: ticketing-app
    environment:
      - DBUSER=${DBUSER}
      - DBPASSWORD=${DBPASS}
      - DBHOST=db
      - DBPORT=${DBPORT}
      - DBNAME=${DBNAME}
      - SERVER=${SERVER}
      - SECRET=${SECRET}
      - REFSECRET=${REFSECRET}
      - EMAIL=${EMAIL_SENDER}
      - PASSWORD=${EMAIL_PASSWORD_SENDER}
    ports:
      - '8888:8888'
    networks:
      - mikti
    volumes:
      - api:/usr/src/app/
    depends_on:
      db:
        condition: service_healthy

networks:
  mikti:
    driver: bridge


volumes:
  mikti-db:
  api:
